name: Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Runs
        if: github.event_type == 'pull_request'
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.7'

      - name: Install dependencies
        run: ./scripts/install_deps.sh

      - name: Lint
        run: make lint

      - name: Tests
        run: ./scripts/test_go.sh
