name: Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    # Run daily at 10:15 am UTC (3:15am PT/5:15am CT)
    - cron: "15 10 * * *"

  workflow_dispatch:

permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Runs
        if: github.event_type == 'pull_request'
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v3.2.0
        with:
          go-version: "^1.16.7"

      - name: Install dependencies
        run: ./scripts/install_deps.sh

      - name: Lint
        run: make lint

      - name: Tests
        run: ./scripts/test_go.sh
        env:
          COVERALLS_TOKEN: ${{ github.token }}

      - name: Test Release
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --snapshot --skip-publish

  scan-source:
    name: scan/source
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel previous runs
        if: github.event_name == 'pull_request'
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v3.2.0
        with:
          go-version: "^1.16.7"

      - name: Install dependencies
        run: ./scripts/install_deps.sh

      - name: Scan with AquaSec Trivy
        run: ./scripts/scan.sh
        continue-on-error: true
