name: Security

on:
  push:
    branches:
      - main

  # If the workflow is modified, run the scans, so that we can test the
  # workflow itself
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/security.yaml

  schedule:
    # Run at 10:15 am UTC (3:15am PT/5:15am CT)
    # Run at 0 minutes 0 hours of every day.
    - cron: "15 10 * * *"

  workflow_dispatch:

permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  scan-source:
    name: scan/source
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel previous runs
        if: github.event_name == 'pull_request'
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.7'

      - name: Install dependencies
        run: ./scripts/install_deps.sh

      - name: Scan with AquaSec Trivy
        run: ./scripts/scan.sh
        continue-on-error: true
